# Generated by Django 2.2.13 on 2021-02-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='user',
        ),
    ]
